### ISSUE TITLE
Entebbe 11/2016 Checklist

### ISSUE THREAD

**Issue by brucellino** [ubuntunet/AnsibleBootCamp#1]
# Checklist for Entebbe 11/2016
- [x] Start the "getting to know you" topic on the forum.
- [ ] Build the learning environment:
  - [x] Deploy Virtual Machines - one per student and one each per facilitator.
  - [ ] Add student ssh keys to the event
    - [ ] Talile Miresa Gamtesa
    - [ ] Hillary   Chituwu
    - [ ] Hellen    Nakawungu
    - [ ] Alex  Mwotil
    - [ ] Marco Maartens
    - [ ] Mohamed   Ali Ahmed
    - [ ] Nyanjau   Kimani
    - [ ] Lalanirina Jean   Andriantsitohaina
    - [ ] Marwa Ibrahim
    - [ ] Damas Makweba
    - [ ] Nosiku    Sikanyika 
    - [ ] Gilberto  Ngoca
    - [ ] Hamim Hamisi
    - [ ] Alima/Haleema Jika
    - [ ] David Gaamuwa
    - [ ] Davy  Abeye
  - [x] Create your inventory file for the event. Add the learner machines to `training-lab` group.
  - [x] Create the `group_vars` and passwords file. You will use this to save sensitive variables.
    - [x] The group variables for the event should be created using the location of the event, e.g. `entebbe.yml`. Put this in `group_vars`
    - [x] The passwords should have the same name, prefixed with "passwords-", _e.g._ : `passwords-entebbe.yml`
  - [x] Run the `training-lab.yml` playbook against the training lab group : `ansible-playbook -i inventories/<event-inventory>.ini -l training-lab training-lab.yml`

**Comment by brucellino** [comment]
discussion and icebreaker topic started at http://discourse.sci-gaia.eu/t/devops-bootcamp-entebbe-nov-2016-tell-us-about-yourself/2367
